//
//  MusicXMLTests.swift
//  allegro
//
//  Created by Nikhil Lele on 2/18/17.
//  Copyright © 2017 gigaunicorn. All rights reserved.
//

import XCTest
@testable import allegro
import Rational
import AEXML

class musicXMLTests: XCTestCase {

    let notes = [
        Note(value: .whole, letter: .C, octave: 4),
        Note(value: .quarter, letter: .A, octave: 4),
        Note(value: .eighth, letter: .G, octave: 4, accidental: .sharp, rest: false),
    ]

    let cases: [(measureIndex: Int, noteIndex: Int, pos: Rational)] = [
        (0, 0, 0),
        (1, 1, 1/4),
        (1, 2, 1/2)
    ]

    override func setUp() {
        super.setUp()
        // Put setup code here. This method is called before the invocation of each test method in the class.

    }

    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }

    // test that XML generated by parser matches what is read from disk
    func testGenerateExample() {
        let store = PartStore(part: Part())
        let parser = MusicXMLParser(store: store)
        store.part.title = "Example0" // match example0.xml
        for c in cases {
            let _ = store.insert(note: notes[c.noteIndex], intoMeasureIndex: c.measureIndex, at: c.pos)
        }

        // load from example0.xml
        let parser2 = MusicXMLParser(store: PartStore(part: Part()))
        guard let part2 = parser2.bundleLoad(filename: "example0") else {
            XCTFail("Unable to load")
            return
        }

        // check that all notes match
        for (i,c) in cases.enumerated() {
            if let note = part2.measures[c.measureIndex].note(at: c.pos) {
                XCTAssertTrue(note == notes[c.noteIndex], "found note \(i)")
            } else {
                XCTFail("Unable to find note \(i)")
            }
        }

        // check that XML matches
        XCTAssertTrue(parser.partDoc.xmlCompact == parser2.partDoc.xmlCompact, "XML matches")
    }

    // test that XML saved to disk can be loaded back the same
    func testSaveLoad() {
        let store = PartStore(part: Part())
        let parser = MusicXMLParser(store: store)
        for c in cases {
            let _ = store.insert(note: notes[c.noteIndex], intoMeasureIndex: c.measureIndex, at: c.pos)
        }
        parser.save(filename: "test")

        // re-load the part
        let parser2 = MusicXMLParser(store: PartStore(part: Part()))
        guard let part2 = parser2.load(filename: "test") else {
            XCTFail("Unable to open file")
            return
        }

        // check that all notes match
        for (i,c) in cases.enumerated() {
            if let note = part2.measures[c.measureIndex].note(at: c.pos) {
                XCTAssertTrue(note == notes[c.noteIndex], "found note \(i)")
            } else {
                XCTFail("Unable to find note \(i)")
            }
        }

        // check tat XML matches
        XCTAssertTrue(parser.partDoc.xmlCompact == parser2.partDoc.xmlCompact, "XML matches")
    }

}
